"""Add manual review fields

Revision ID: 24865f4ccd0e
Revises: 
Create Date: 2024-11-21 17:09:13.500570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24865f4ccd0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_records', sa.Column('needs_manual_review', sa.Boolean(), nullable=True))
    op.add_column('patient_records', sa.Column('error_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_records', 'error_details')
    op.drop_column('patient_records', 'needs_manual_review')
    # ### end Alembic commands ###
